src/accounts/models.py
from datetime import datetime

from flask_login import UserMixin

from src import bcrypt, db

class User(UserMixin, db.Model):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String, unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)
    created_on = db.Column(db.DateTime, nullable=False)
    is_admin = db.Column(db.Boolean, nullable=False, default=False)
    is_confirmed = db.Column(db.Boolean, nullable=False, default=False)
    is_subscribed = db.Column(db.Boolean, nullable=False, default=True)
    confirmed_on = db.Column(db.DateTime, nullable=True)

    def __init__(
        self, email, password, is_admin=False, is_confirmed=False, confirmed_on=None, is_subscribed=True
    ):
        self.email = email
        self.password = bcrypt.generate_password_hash(password)
        self.created_on = datetime.now()
        self.is_admin = is_admin
        self.is_confirmed = is_confirmed
        self.is_subscribed = is_subscribed
        self.confirmed_on = confirmed_on

    def __repr__(self):
        if self.is_admin:
            return f"<admin {self.email}>"
        return f"<email {self.email}>"

src/core/models.py
from src import db

class Event(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    location = db.Column(db.String(100), nullable=False)
    time_date = db.Column(db.DateTime, nullable=False)

src/accounts/forms.py
from flask_wtf import FlaskForm
from wtforms import EmailField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from src.accounts.models import User


class LoginForm(FlaskForm):
    email = EmailField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])


class RegisterForm(FlaskForm):
    email = EmailField(
        "Email", validators=[DataRequired(), Email(message=None), Length(min=6, max=40)]
    )
    password = PasswordField(
        "Password", validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        "Repeat password",
        validators=[
            DataRequired(),
            EqualTo("password", message="Passwords must match."),
        ],
    )

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        if self.password.data != self.confirm.data:
            self.password.errors.append("Passwords must match")
            return False
        return True

src/core/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.fields.datetime import DateField, TimeField
from wtforms.validators import DataRequired

# from src.accounts.models import User


class CreateEventForm(FlaskForm):
    title = StringField("Event Title", validators=[DataRequired()])
    location = StringField("Location", validators=[DataRequired()])
    date = DateField('Event Date', format='%Y-%m-%d', validators=[DataRequired()])
    time = TimeField('Event Time', validators=[DataRequired()])

src/__init__.py
from decouple import config
from flask import Flask, render_template
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
import os
from dotenv import load_dotenv

app = Flask(__name__)
load_dotenv()
# dotenv SECRET_KEY=SomeRandomKey 
app.config.from_object(config("APP_SETTINGS"))
app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')

# app.config.from_object()
login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
mail = Mail(app)
db = SQLAlchemy(app)
migrate = Migrate(app, db)

# Registering blueprints
from src.accounts.views import accounts_bp
from src.core.views import core_bp
from src.minecraft.views import minecraft_bp
from src.simulations.views import simulations_bp

app.register_blueprint(accounts_bp)
app.register_blueprint(core_bp)
app.register_blueprint(minecraft_bp)
app.register_blueprint(simulations_bp)

from .accounts.models import User
from .core.models import Event

login_manager.login_view = "accounts.login"
login_manager.login_message_category = "danger"


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


########################
#### error handlers ####
########################


@app.errorhandler(401)
def unauthorized_page(error):
    return render_template("errors/401.html"), 401


@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500

src/accounts/views.py
from datetime import datetime

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user

from src import bcrypt, db
from src.accounts.models import User
from src.accounts.token import confirm_token, generate_token
from src.utils.decorators import logout_required
from src.utils.email import send_email

from .forms import LoginForm, RegisterForm

accounts_bp = Blueprint("accounts", __name__)

@accounts_bp.route("/register", methods=["GET", "POST"])
@logout_required
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        # Coverting email to lowercase
        user = User(email=form.email.data.lower(), password=form.password.data)
        db.session.add(user)
        db.session.commit()
        token = generate_token(user.email)
        confirm_url = url_for("accounts.confirm_email", token=token, _external=True)
        html = render_template("accounts/confirm_email.html", confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(user.email, subject, html)

        login_user(user)

        flash("A confirmation email has been sent via email.", "success")
        return redirect(url_for("accounts.inactive"))

    return render_template("accounts/register.html", form=form)


@accounts_bp.route("/login", methods=["GET", "POST"])
@logout_required
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user and bcrypt.check_password_hash(user.password, request.form["password"]):
            login_user(user)
            print(user)
            return redirect(url_for("core.home"))
        else:
            flash("Invalid email and/or password.", "danger")
            return render_template("accounts/login.html", form=form)
    return render_template("accounts/login.html", form=form)


@accounts_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out.", "success")
    return redirect(url_for("accounts.login"))


@accounts_bp.route("/confirm/<token>")
@login_required
def confirm_email(token):
    if current_user.is_confirmed:
        flash("Account already confirmed.", "success")
        return redirect(url_for("core.home"))
    email = confirm_token(token)
    user = User.query.filter_by(email=current_user.email).first_or_404()
    if user.email == email:
        user.is_confirmed = True
        user.confirmed_on = datetime.now()
        db.session.add(user)
        db.session.commit()
        flash("You have confirmed your account. Thanks!", "success")
    else:
        flash("The confirmation link is invalid or has expired.", "danger")
    return redirect(url_for("core.home"))


@accounts_bp.route("/inactive")
@login_required
def inactive():
    if current_user.is_confirmed:
        return redirect(url_for("core.home"))
    return render_template("accounts/inactive.html")


@accounts_bp.route("/resend")
@login_required
def resend_confirmation():
    if current_user.is_confirmed:
        flash("Your account has already been confirmed.", "success")
        return redirect(url_for("core.home"))
    token = generate_token(current_user.email)
    confirm_url = url_for("accounts.confirm_email", token=token, _external=True)
    html = render_template("accounts/confirm_email.html", confirm_url=confirm_url)
    subject = "Please confirm your email"
    send_email(current_user.email, subject, html)
    flash("A new confirmation email has been sent.", "success")
    return redirect(url_for("accounts.inactive"))

src/core/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from src.utils.decorators import check_is_confirmed, admin_required

from src.accounts.models import User
from src.core.models import Event
from src import db
from flask_login import current_user, login_required
from .forms import CreateEventForm

from src.utils.email import send_email

from datetime import datetime

core_bp = Blueprint("core", __name__)


@core_bp.route("/")
def home():
    return render_template("core/index.html")


@core_bp.route("/emails")
@login_required
@check_is_confirmed
def emails():
    return render_template("core/emails.html")

@core_bp.route("/schedule", methods=["GET", "POST"])
def schedule():
    form = CreateEventForm(request.form)
    if form.validate_on_submit() and current_user.is_admin:
        event_datetime = datetime.combine(form.date.data, form.time.data)
        print(f"{current_user} wants to create {form.title.data} at {form.location.data} on {event_datetime}")
        event = Event(title=form.title.data, location=form.location.data, time_date=event_datetime)
        db.session.add(event)
        db.session.commit()
        form.title.data = ""
        form.location.data = ""
        form.date.data = ""
        form.time.data = ""

    events = Event.query.all()
    return render_template("core/schedule.html", events=events, form=form)

@core_bp.route("/rsvp/<int:event_id>/<response>")
@login_required
@check_is_confirmed
def rsvp(event_id=-1, response="blank"):
    print(f"{current_user} responded {response} to event {event_id}")
    return redirect(url_for('core.schedule'))


@core_bp.route("/subscribe/")
@login_required
@check_is_confirmed
def subscribe():
    print(f"{current_user} is subscribing to the email list")
    User.query.filter(User.id == current_user.id).update({"is_subscribed": True})
    db.session.commit()

    html = render_template("emails/meeting_today_email.html", user=current_user)
    subject = "You have received this random email because you subscribed to the email list"
    send_email(current_user.email, subject, html)

    return redirect(url_for('core.emails'))

@core_bp.route("/delete_event/<int:event_id>")
@login_required
@admin_required
@check_is_confirmed
def delete_event(event_id=-1):
    print(f"{current_user} wants to delete {event_id}")
    Event.query.filter(Event.id == event_id).delete()
    db.session.commit()
    return redirect(url_for('core.schedule'))

@core_bp.route("/delete_user/<int:user_id>")
@login_required
@admin_required
@check_is_confirmed
def delete_user(user_id=-1):
    print(f"{current_user} wants to delete {user_id}")
    User.query.filter(User.id == user_id).delete()
    db.session.commit()
    return redirect(url_for('core.admin'))

@core_bp.route("/admin")
@login_required
@admin_required
@check_is_confirmed
def admin():
    return render_template("core/admin.html", users=User.query.all())

src/minecraft/views.py
from flask import Blueprint, render_template
from flask_login import login_required

from src.utils.decorators import check_is_confirmed

minecraft_bp = Blueprint("minecraft", __name__)


@minecraft_bp.route("/minecraft")
@login_required
@check_is_confirmed
def home():
    return render_template("minecraft/index.html")


@minecraft_bp.route("/minecraft/info")
@login_required
@check_is_confirmed
def info():
    return render_template("minecraft/info.html")

src/simulations/views.py
from flask import Blueprint, render_template
from flask_login import login_required

from src.utils.decorators import check_is_confirmed

simulations_bp = Blueprint("simulations", __name__)


@simulations_bp.route("/simulations/")
def home():
    return render_template("simulations/index.html")

@simulations_bp.route("/simulations/double_pendulum")
def double_pendulum():
    return render_template("simulations/double_pendulum.html")

@simulations_bp.route("/simulations/color_bounce")
def color_bounce():
    return render_template("simulations/color_bounce.html")

@simulations_bp.route("/simulations/gravity")
def gravity():
    return render_template("simulations/gravity.html")

@simulations_bp.route("/simulations/circular_projectiles")
def circular_projectiles():
    return render_template("simulations/circular_projectiles.html")

@simulations_bp.route("/simulations/pendulum_tunnel")
def pendulum_tunnel():
    return render_template("simulations/pendulum_tunnel.html")

@simulations_bp.route("/simulations/oscillating_charges")
def oscillating_charges():
    return render_template("simulations/oscillating_charges.html")

src/templates/_base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8">
    <title>SPS Computer Science Club</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <!-- styles -->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='core/css/index.css')}}">
    {% block css %}{% endblock %}
</head>
<body>

{% include "navigation.html" %}

<div class="container">

    <br>

    <!-- messages -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        </div>
        <div class="col-md-4"></div>
    </div>
    {% endif %}
    {% endwith %}

    <!-- child template -->
    {% block content %}{% endblock %}

</div>

<!-- scripts -->
<script src="https://code.jquery.com/jquery-3.6.1.min.js" type="text/javascript"></script>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
{% block js %}{% endblock %}

</body>
</html>

src/templates/navigation.html
<!-- Navigation -->
<link rel="stylesheet" href="{{url_for('static', filename='core/css/navigation.css')}}">

<header style="position: absolute; top: 0; width: 100%; height:8%" class="p-3 text-bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{{ url_for('core.home') }}" class="nav-link px-2 text-secondary">Home</a></li>
                <li><a href="{{ url_for('core.schedule') }}" class="nav-link px-2 text-secondary">Schedule</a></li>
                <li><a href="{{ url_for('minecraft.info') }}" class="nav-link px-2 text-secondary">Minecraft</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle px-2 text-secondary" href="#" role="button">Projects</a>
                    <div class="dropdown-content">
                        <a class="dropdown-item" href="{{ url_for('simulations.double_pendulum') }}">
                            <img src="{{url_for('static', filename='simulations/images/double_pendulum_preview.png')}}" alt="Double Pendulum Simulation" style="width: 100px; height: 100px;">
                            Double Pendulum
                        </a>
                        <a class="dropdown-item" href="{{ url_for('simulations.color_bounce') }}">
                            <img src="{{url_for('static', filename='simulations/images/bounce_preview.png')}}" alt="Color Bounce Simulation" style="width: 100px; height: 100px;">
                            Color Bounce
                        </a>
                        <a class="dropdown-item" href="{{ url_for('simulations.circular_projectiles') }}">
                            <img src="{{url_for('static', filename='simulations/images/circular_projectiles_preview.png')}}" alt="Circular Projectiles Simulation" style="width: 100px; height: 100px;">
                            Circular Projectiles
                        </a>
                        <a class="dropdown-item" href="{{ url_for('simulations.gravity') }}">
                            <img src="{{url_for('static', filename='simulations/images/gravity_preview.png')}}" alt="Gravity Simulation" style="width: 100px; height: 100px;">
                            Gravity
                        </a>
                        <a class="dropdown-item" href="{{ url_for('simulations.pendulum_tunnel') }}">
                            <img src="{{url_for('static', filename='simulations/images/pendulum_tunnel_preview.png')}}" alt="Pendulum Tunnel" style="width: 100px; height: 100px;">
                            Pendulum Tunnel
                        </a>
<!--                        <a class="dropdown-item" href="{{ url_for('simulations.oscillating_charges') }}">-->
<!--                            <img src="{{url_for('static', filename='simulations/images/oscillating_charges_preview.png')}}" alt="Oscillating Charges" style="width: 100px; height: 100px;">-->
<!--                            Oscillating Charges-->
<!--                        </a>-->
                    </div>
                </li>
                <li><a href="{{ url_for('core.emails') }}" class="nav-link px-2 text-secondary">Emails</a></li>
            </ul>

            <div class="text-end">
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('accounts.logout') }}"><button type="button" class="btn btn-danger me-2">Logout</button></a>
                {% else %}
                <a href="{{ url_for('accounts.login') }}"><button type="button" class="btn btn-outline-light me-2">Login</button></a>
                <a href="{{ url_for('accounts.register') }}"><button type="button" class="btn btn-success">Sign up</button></a>
                {% endif %}
            </div>
        </div>
    </div>
</header>